name: Continuous Deployment
on:
  push:
    tags:
      - '*'
jobs:
  test:
    strategy:
      matrix:
        java-version: [ 8, 11, 17, 21 ]
    name: Test using Java ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          lein: 2.11.2
      - name: Java version
        run: java -version
      - name: Install dependencies
        run: lein deps
      - name: Run clj tests
        run: lein test
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          lein: 2.11.2
      - name: Install dependencies
        run: lein deps
      - name: Publish on Clojars
        run: lein release
        env:
          CLOJARS_USERNAME: gustavo-flor
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_DEPLOY_TOKEN }}
